apiVersion: apps/v1
kind: Deployment
metadata:
  name: supermariogame-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supermariogame
  template:
    metadata:
      labels:
        app: supermariogame
    spec:
      containers:
      - image: raghuthesecurityexpert/supermariogitopsproject:3
        name: supermariogame-container
        ports:
        - containerPort: 8080
 
---
apiVersion: v1
kind: Service
metadata:
  name: supermariogame-service
spec:
  selector:
    app: supermariogame
  ports:
  - protocol: TCP
    port: 8600  # <-- Change this line to your desired port
    targetPort: 8080
  type: LoadBalancer